services:
  - type: web
    name: ai-news-summarizer

    runtime: python

    plan: free

    autoDeploy: true

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /health

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: GNEWS_API_KEY
        sync: false
